# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SIR_Cpp <- function(t, alpha, beta, S0, I0, Ap1, Bp1, direction, nblocks, tol, computeMode, nThreads) {
    .Call('_MultiBDPureBirth_SIR_Cpp', PACKAGE = 'MultiBDPureBirth', t, alpha, beta, S0, I0, Ap1, Bp1, direction, nblocks, tol, computeMode, nThreads)
}

SIR_pure_birth_Cpp <- function(t, alpha, beta, S0, I0, Ap1, Bp1, direction, nblocks, tol, computeMode, nThreads) {
    .Call('_MultiBDPureBirth_SIR_pure_birth_Cpp', PACKAGE = 'MultiBDPureBirth', t, alpha, beta, S0, I0, Ap1, Bp1, direction, nblocks, tol, computeMode, nThreads)
}

bb_lt_invert_Cpp <- function(t, lambda1, lambda2, Ap1, Bp1, direction, nblocks, tol, computeMode, nThreads) {
    .Call('_MultiBDPureBirth_bb_lt_invert_Cpp', PACKAGE = 'MultiBDPureBirth', t, lambda1, lambda2, Ap1, Bp1, direction, nblocks, tol, computeMode, nThreads)
}

bbd_lt_invert_Cpp <- function(t, a0, b0, lambda1, lambda2, mu2, gamma, x, y, A, Bp1, nblocks, tol, computeMode, nThreads, maxdepth) {
    .Call('_MultiBDPureBirth_bbd_lt_invert_Cpp', PACKAGE = 'MultiBDPureBirth', t, a0, b0, lambda1, lambda2, mu2, gamma, x, y, A, Bp1, nblocks, tol, computeMode, nThreads, maxdepth)
}

